### ISSUE TITLE
Python 3 Support

### ISSUE THREAD

**Issue by benjaminbecker** [GovDataOfficial/ckanext-dcatde#12]
Are there plans to implement a version of this extension which is executable in Python 3?

**Comment by AntjeM** [comment]
Yes, that will be part of the switch to a Python 3 capable CKAN version. But there is no date for this yet.

**Comment by benjaminbecker** [comment]
I did a quick test with `2to3`. For me this worked.

**Comment by AntjeM** [comment]
We will adjust the extensions while we update to CKAN 2.9 or 3.0, but we have not yet terminated that.

**Comment by xellos866** [comment]
Hello,

we have created a fork of your extension and upgraded it for Python3 support. If you are interested we can create a Pull Request. Otherwise you can view or use (part of) the code. 

[link to forked brach "ckan.3.0-v4.6.1"](https://github.com/dkd/ckanext-dcatde/tree/ckan.3.0-v4.6.1)

_Note_: We haven't tested (but upgraded) the components: "harvesters" and "triplestore", because we don't use these components.
 
regards

**Comment by seitenbau-govdata** [comment]
Python 3 support was added with version `5.1.0`. Fixed by https://github.com/GovDataOfficial/ckanext-dcatde/commit/c570398b337f04e7b223022dc4931eec98ee8ee5
