### ISSUE TITLE
Required ckanext-dcat version

### ISSUE THREAD

**Issue by MarijaKnezevic** [GovDataOfficial/ckanext-dcatde#15]
Hey
I have question regarding `ckanext-dcatde` and `ckanext-dcat` version.
In [Getting started](https://github.com/GovDataOfficial/ckanext-dcatde#getting-started) is written that it requires `ckanext-dcat` release greather than v.1.0.0 and in the [base-requirements.txt](https://github.com/GovDataOfficial/ckanext-dcatde/blob/master/base-requirements.txt)  is explicitly defined `ckanext-dcat==1.4.0`.
Is the `ckanext-dcat` working for all versions greather than v.1.0.0, or it should be used just the 1.4.0? Is there any suggestions which version is recommended?

Thank you very much

**Comment by thorge** [comment]
Same question here. ckanext-dcat already released version [1.5.0](https://github.com/ckan/ckanext-dcat/commit/1b23fa277d2e556ffe591a89550d59a4251ff7c1).

**Comment by seitenbau-govdata** [comment]
The current version `5.13.0` of `ckanext-dcatde` should be compatible with all `ckanext-dcat` versions `1.x` up to `1.4.0`. However `1.5.0` is not yet recommended because the implementation of `dcat:accessServices` has been moved from `ckanext-dcatde` to `ckanext-dcat` resulting in duplicated implementations. We don't know yet if this might cause problems. A new version of `ckanext-dcatde` containing a solution for this will be released in the next couple of weeks.
As a rule of thumb we recommended the usage of the version specified in the `base-requirements.txt` since this combination of versions is the only one we have tested.

**Comment by MarijaKnezevic** [comment]
> The current version `5.13.0` of `ckanext-dcatde` should be compatible with all `ckanext-dcat` versions `1.x` up to `1.4.0`. However `1.5.0` is not yet recommended because the implementation of `dcat:accessServices` has been moved from `ckanext-dcatde` to `ckanext-dcat` resulting in duplicated implementations. We don't know yet if this might cause problems. A new version of `ckanext-dcatde` containing a solution for this will be released in the next couple of weeks. As a rule of thumb we recommended the usage of the version specified in the `base-requirements.txt` since this combination of versions is the only one we have tested.

Thank you very much
